releasetools: remove custom releasetools
This was written to bypass the treble compatibility check for Android 9
based releases.

We needed that since we wanted to have 4.19 kernel on Android 9, which
is not compatible (the kernel is too recent).

This is no longer needed, so remove it.

Moreover, this breaks "make dist":

      File "/srv/data/mkorpershoek/aosp-11/out/target/product/quartz/obj/PACKAGING/target_files_intermediates/aosp_quartz-target_files-eng.mkorpershoek/META/releasetools.py", line 9, in FullOTA_InstallBegin
        params.info_dict['build.prop']['ro.treble.enabled'] = 'false'
    TypeError: 'PartitionBuildProps' object does not support item assignment

Test: make dist
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>