i300a_sb30: enable OPTEE and TEE_KEYMASTER_GATEKEEPER
i300a_sb30 has a persist partition defined in their partitions.yaml,
however, we don't generate a persist.img in OUT.

Because of that, flashing fails with:

flashing persist=persist.img
error: cannot load 'persist.img': No such file or directory

Fix the flashing by configuring OPTEE_ENABLE, which generates us a persist.img.

Test: m && ls out/target/product/i300a_sb30/persist.img
Bug: RITA-700
Reported-by: Steve Nare <snare@baylibre.com>
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>