build: set TARGET_BOOTLOADER_BOARD_NAME
TARGET_BOOTLOADER_BOARD_NAME is required to run VTS on Android9.

Without defining the TARGET_BOOTLOADER_BOARD_NAME variable, vts fails
with:

07-09 16:43:53 E/CommandScheduler: Failed to get device information
    java.lang.RuntimeException: Failed to get device information
    at com.android.tradefed.testtype.VtsMultiDeviceTest.generateJsonDeviceItem(VtsMultiDeviceTest.java:585)
    at com.android.tradefed.testtype.VtsMultiDeviceTest.updateVtsRunnerTestConfig(VtsMultiDeviceTest.java:713)
    at com.android.tradefed.testtype.VtsMultiDeviceTest.doRunTest(VtsMultiDeviceTest.java:1106)
    at com.android.tradefed.testtype.VtsMultiDeviceTest.run(VtsMultiDeviceTest.java:639)
    at com.android.compatibility.common.tradefed.testtype.ModuleDef.run(ModuleDef.java:263)
    at com.android.compatibility.common.tradefed.testtype.ModuleDefMultiDevice.run(ModuleDefMultiDevice.java:143)
    at com.android.compatibility.common.tradefed.testtype.CompatibilityTest.run(CompatibilityTest.java:491)
    at com.android.tradefed.invoker.InvocationExecution.runTests(InvocationExecution.java:384)
    at com.android.tradefed.invoker.TestInvocation.prepareAndRun(TestInvocation.java:357)
    at com.android.tradefed.invoker.TestInvocation.performInvocation(TestInvocation.java:204)
    at com.android.tradefed.invoker.TestInvocation.invoke(TestInvocation.java:662)
at com.android.tradefed.command.CommandScheduler$InvocationThread.run(CommandScheduler.java:566)

Test: ./vts-tradefed run commandAndExit vts-kernel --module VtsKernelApiSysfsTest
Bug: RITA-315
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>